# Site settings
title: Julyvee Dev
description: >- 
  Personal developer blog for Julia Valder, a software engineer at Microsoft in the 
  Commercial Software Engineering Organization
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://julyvee.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: cse.jpg
hero-title: Julia Valder
hero-description: >- 
  Software engineer at Microsoft in the 
  Commercial Software Engineering Organization

# Author - Creator
author-name: Julia Valder
author-image: juliavalder.jpg
about-author: Julia Valder is a software engineer at Microsoft in the Commercial Software Engineering Organization. 
author-github: https://www.github.com/julyvee
author-linkedin: https://linkedin.com/in/julia-valder

# Social Media Links (Links are located in hero and footer)
linkedin: https://linkedin.com/in/julia-valder
github: https://www.github.com/julyvee

# Contact Form Settings
contact-subtitle: Pok pok listicle meggings, gluten-free deep v you probably haven't heard of them taxidermy iPhone gentrify seitan. Kogi cornhole enamel. # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
